spring:
  application:
    name: gateway-service
  config:
    import: optional:configserver:http://localhost:8888  # This is the modern way

server:
  port: 8080

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS
  info:
    env:
      enabled: true


info:
  apps:
    name: gateway
    version: 2


logging:
  level:
    root: INFO
    org.springframework.cloud.gateway: TRACE
    org.springframework.cloud.gateway.route.RouteDefinitionLocator: DEBUG
    org.springframework.cloud.gateway.route.RouteDefinitionRouteLocator: DEBUG
