spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri:




#  cloud:
#    gateway:
#      routes:
#        - id: school-service
#          uri: lb://SCHOOL-SERVICE
#          predicates:
#            - Path=/schools/**
#        - id: student-service
#          uri: lb://STUDENT-SERVICE
#          predicates:
#            - Path=/students/**
#      discovery:
#        locator:
#          enabled: true
#          lower-case-service-id: true
  application:
    name: gateway
  config:
    import: optional:configserver:http://localhost:8888


#          uri: lb://STUDENT-SERVICE
#          uri: lb://SCHOOL-SERVICE

server:
  port: 8080

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS
  info:
    env:
      enabled: true


info:
  apps:
    name: gateway
    version: 2

#
#logging:
#  level:
#    root: INFO
#    org.springframework.cloud.gateway: TRACE
#    org.springframework.cloud.gateway.route.RouteDefinitionLocator: TRACE
#    org.springframework.cloud.gateway.route.RouteDefinitionRouteLocator: TRACE
