spring:
  cloud:
    gateway:
      routes:
        - id: school-service
          uri: lb://SCHOOL-SERVICE
          predicates:
            - Path=/schools/**
        - id: student-service
          uri: lb://STUDENT-SERVICE
          predicates:
            - Path=/students/**

      discovery:
        locator:
          enabled: true
          lower-case-service-id: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    fetch-registry: true
    register-with-eureka: true
  instance:
    prefer-ip-address: true

management:
  endpoints:
    web:
      exposure:
        include: "*"
      base-path: /actuator
  endpoint:
    gateway:
      enabled: true
    health:
      show-details: always
    routes:
      enabled: true

server:
  port: 8080

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    org.springframework.cloud.gateway.route: TRACE
    org.springframework.cloud.gateway.handler: TRACE
    org.springframework.cloud.loadbalancer: DEBUG
    reactor.netty: DEBUG