spring:
  cloud:
    gateway:
      routes:
        - id: school-service
          uri: lb://SCHOOL-SERVICE
          predicates:
            - Path=/schools/**
        - id: student-service
          uri: lb://STUDENT-SERVICE
          predicates:
            - Path=/students/**
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

server:
  port: 8080

logging:
  level:
    root: INFO
    org.springframework.cloud.gateway: TRACE
    org.springframework.cloud.gateway.route.RouteDefinitionLocator: INFO
